# Generated by Django 4.2.7 on 2023-11-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_alter_modelo_configuracion_motor_alter_modelo_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='año',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='cilindrada_motor',
        ),
        migrations.AddField(
            model_name='modelo',
            name='año_fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='año_inicio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='caballos_fuerza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='cilindrada_motor_litros',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='generacion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='torque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='configuracion_motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.marca'),
        ),
    ]
