# Generated by Django 4.2.7 on 2023-11-10 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0002_marca_logo'),
        ('autos', '0003_marca_remove_modelo_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcas.marca'),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
