# Generated by Django 4.2.7 on 2023-11-14 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_alter_modelo_marca_delete_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 14, 2, 2, 50, 95275, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
