# Generated by Django 4.2.7 on 2023-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marcas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marca",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="marcas/logos/"),
        ),
    ]
