# Generated by Django 4.2.7 on 2023-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0002_marca_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='año_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
