# Generated by Django 4.2.7 on 2023-11-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0003_marca_año_creacion_marca_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(upload_to='marcas/logos/'),
        ),
    ]
