# Generated by Django 4.2.7 on 2023-11-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0005_rename_año_creacion_marca_año_fundación'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='fundador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='año_fundación',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pais_origen',
            field=models.CharField(max_length=50),
        ),
    ]
